//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kids_school.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class kidtable
    {
        [DisplayName("Id")]
        [Required(ErrorMessage = "Id is required field")]
        public int id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Name is required field")]
        public string name { get; set; }

        [DisplayName("Father Name")]
        [Required(ErrorMessage = "Father Name is required field")]
        public string fname { get; set; }

        [DisplayName("Classes")]
        [Required(ErrorMessage = "Classes is required field")]
        public int classes { get; set; }

        [DisplayName("Contact No.")]
        [Required(ErrorMessage = "Contact number is required field")]
        public string cnumber { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "Address is required field")]
        public string address { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Emaill is required field")]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",ErrorMessage ="Invalid Email")]
        public string email { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required field")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm password is required field")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Paaword is not identical ")]

        public string confirm_password { get; set; }
    }
}
