//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kids_school.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class query
    {
        public int id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage="Name is required..")]
        public string name { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage ="Email is Required..")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [DisplayName("Message")]
        [Required(ErrorMessage ="Message is required..")]
        public string message { get; set; }
    }
}
